// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_bds_0_6.go at 2019-08-15 10:36:54.1086983 +0300 EEST m=+0.005974501
package messages

import (
	"github.com/twuillemin/modes/pkg/bds/adsb"
	"testing"
)

func TestDetectAndReadFormat05V0Valid(t *testing.T) {

	data := buildValidBDS06V0Message()
	data[0] = data[0] | 0x28

	msg, adsbResult, err := ReadBDS06(adsb.Level0OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format05V0); !ok {
		t.Errorf("expected a message of type Format05V0, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level0OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat05V1Valid(t *testing.T) {

	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x28

	msg, adsbResult, err := ReadBDS06(adsb.Level1OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format05V1); !ok {
		t.Errorf("expected a message of type Format05V1, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level1OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat05V2Valid(t *testing.T) {

	data := buildValidBDS06V2Message()
	data[0] = data[0] | 0x28

	msg, adsbResult, err := ReadBDS06(adsb.Level2, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format05V2); !ok {
		t.Errorf("expected a message of type Format05V2, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level2 {
		t.Errorf("expected adsbLevel to be returned as Level2, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat06V0Valid(t *testing.T) {

	data := buildValidBDS06V0Message()
	data[0] = data[0] | 0x30

	msg, adsbResult, err := ReadBDS06(adsb.Level0OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format06V0); !ok {
		t.Errorf("expected a message of type Format06V0, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level0OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat06V1Valid(t *testing.T) {

	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x30

	msg, adsbResult, err := ReadBDS06(adsb.Level1OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format06V1); !ok {
		t.Errorf("expected a message of type Format06V1, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level1OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat06V2Valid(t *testing.T) {

	data := buildValidBDS06V2Message()
	data[0] = data[0] | 0x30

	msg, adsbResult, err := ReadBDS06(adsb.Level2, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format06V2); !ok {
		t.Errorf("expected a message of type Format06V2, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level2 {
		t.Errorf("expected adsbLevel to be returned as Level2, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat07V0Valid(t *testing.T) {

	data := buildValidBDS06V0Message()
	data[0] = data[0] | 0x38

	msg, adsbResult, err := ReadBDS06(adsb.Level0OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format07V0); !ok {
		t.Errorf("expected a message of type Format07V0, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level0OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat07V1Valid(t *testing.T) {

	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x38

	msg, adsbResult, err := ReadBDS06(adsb.Level1OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format07V1); !ok {
		t.Errorf("expected a message of type Format07V1, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level1OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat07V2Valid(t *testing.T) {

	data := buildValidBDS06V2Message()
	data[0] = data[0] | 0x38

	msg, adsbResult, err := ReadBDS06(adsb.Level2, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format07V2); !ok {
		t.Errorf("expected a message of type Format07V2, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level2 {
		t.Errorf("expected adsbLevel to be returned as Level2, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat08V0Valid(t *testing.T) {

	data := buildValidBDS06V0Message()
	data[0] = data[0] | 0x40

	msg, adsbResult, err := ReadBDS06(adsb.Level0OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format08V0); !ok {
		t.Errorf("expected a message of type Format08V0, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level0OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat08V1Valid(t *testing.T) {

	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x40

	msg, adsbResult, err := ReadBDS06(adsb.Level1OrMore, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format08V1); !ok {
		t.Errorf("expected a message of type Format08V1, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level1OrMore {
		t.Errorf("expected adsbLevel to be returned as Level0OrMore, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectAndReadFormat08V2Valid(t *testing.T) {

	data := buildValidBDS06V2Message()
	data[0] = data[0] | 0x40

	msg, adsbResult, err := ReadBDS06(adsb.Level2, false, false, data)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := msg.(*Format08V2); !ok {
		t.Errorf("expected a message of type Format08V2, but got %v instead", msg.GetMessageFormat().ToString())
	}
	if adsbResult != adsb.Level2 {
		t.Errorf("expected adsbLevel to be returned as Level2, but got %v instead", adsbResult.ToString())
	}
}

func TestDetectBadFormat(t *testing.T) {

	// make a Format 01 message
	data := buildValidBDS06V0Message()
	data[0] = (data[0] & 0x07) | 0x08

	_, _, err := ReadBDS06(adsb.Level0OrMore, false, false, data)
	if err == nil {
		t.Fatal("Expected an error while reading a message with format 01, but message was read")
	}
}
