// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_v1.go at 2024-06-01 14:32:29.0918042 +0300 EEST m=+0.002708301
package messages

import (
	"testing"
)

func TestReadFormat06V1Valid(t *testing.T) {

	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x30

	msg, err := ReadFormat06V1(false, data)
	if err != nil {
		t.Fatal(err)
	}

	isBDS06V1Valid(t, msg)
}

func TestReadFormat06V1TooShort(t *testing.T) {

	// Get too short data
	data := buildValidBDS06V1Message()[:6]
	data[0] = data[0] | 0x30

	_, err := ReadFormat06V1(false, data)
	if err == nil {
		t.Error(err)
	}
}

func TestReadFormat06V1BadCode(t *testing.T) {

	// Message code 1
	data := buildValidBDS06V1Message()
	data[0] = data[0] | 0x01

	_, err := ReadFormat06V1(false, data)
	if err == nil {
		t.Error(err)
	}
}
