// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_v2.go at 2024-06-02 01:03:31.0002548 +0300 EEST m=+0.005309401
package messages

import (
	"testing"
)

func TestReadFormat22V2Valid(t *testing.T) {

	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0xB0

	msg, err := ReadFormat22V2(data)
	if err != nil {
		t.Fatal(err)
	}

	isBDS05V2Valid(t, msg)
}

func TestReadFormat22V2TooShort(t *testing.T) {

	// Get too short data
	data := buildValidBDS05V2Message()[:6]
	data[0] = data[0] | 0xB0

	_, err := ReadFormat22V2(data)
	if err == nil {
		t.Error(err)
	}
}

func TestReadFormat22V2BadCode(t *testing.T) {

	// Message code 1
	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0x01

	_, err := ReadFormat22V2(data)
	if err == nil {
		t.Error(err)
	}
}
