// Package adsb holds the definition for the ADSB messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_formats_reference.go at 2019-07-22 20:48:16.5941225 +0300 EEST m=+0.006952101
package adsb

import (
	"github.com/twuillemin/modes/pkg/bds/bds"
)

// ------------------------------------------------------------------------------------
//
//                                Format01
//
// ------------------------------------------------------------------------------------

// Format01V0OrMore is the definition of a message at Format01 for ADSB Level0OrMore
var Format01V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  1,
	register:  bds.BDS08,
	adsbLevel: Level0OrMore,
}

// ------------------------------------------------------------------------------------
//
//                                Format02
//
// ------------------------------------------------------------------------------------

// Format02V0OrMore is the definition of a message at Format02 for ADSB Level0OrMore
var Format02V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  2,
	register:  bds.BDS08,
	adsbLevel: Level0OrMore,
}

// ------------------------------------------------------------------------------------
//
//                                Format03
//
// ------------------------------------------------------------------------------------

// Format03V0OrMore is the definition of a message at Format03 for ADSB Level0OrMore
var Format03V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  3,
	register:  bds.BDS08,
	adsbLevel: Level0OrMore,
}

// ------------------------------------------------------------------------------------
//
//                                Format04
//
// ------------------------------------------------------------------------------------

// Format04V0OrMore is the definition of a message at Format04 for ADSB Level0OrMore
var Format04V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  4,
	register:  bds.BDS08,
	adsbLevel: Level0OrMore,
}

// ------------------------------------------------------------------------------------
//
//                                Format05
//
// ------------------------------------------------------------------------------------

// Format05V0 is the definition of a message at Format05 for ADSB Level0Exactly
var Format05V0 = adsbFormatReferenceDefinition{
	typeCode:  5,
	register:  bds.BDS06,
	adsbLevel: Level0Exactly,
}

// Format05V1 is the definition of a message at Format05 for ADSB Level1Exactly
var Format05V1 = adsbFormatReferenceDefinition{
	typeCode:  5,
	register:  bds.BDS06,
	adsbLevel: Level1Exactly,
}

// Format05V2 is the definition of a message at Format05 for ADSB Level2
var Format05V2 = adsbFormatReferenceDefinition{
	typeCode:  5,
	register:  bds.BDS06,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format06
//
// ------------------------------------------------------------------------------------

// Format06V0 is the definition of a message at Format06 for ADSB Level0Exactly
var Format06V0 = adsbFormatReferenceDefinition{
	typeCode:  6,
	register:  bds.BDS06,
	adsbLevel: Level0Exactly,
}

// Format06V1 is the definition of a message at Format06 for ADSB Level1Exactly
var Format06V1 = adsbFormatReferenceDefinition{
	typeCode:  6,
	register:  bds.BDS06,
	adsbLevel: Level1Exactly,
}

// Format06V2 is the definition of a message at Format06 for ADSB Level2
var Format06V2 = adsbFormatReferenceDefinition{
	typeCode:  6,
	register:  bds.BDS06,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format07
//
// ------------------------------------------------------------------------------------

// Format07V0 is the definition of a message at Format07 for ADSB Level0Exactly
var Format07V0 = adsbFormatReferenceDefinition{
	typeCode:  7,
	register:  bds.BDS06,
	adsbLevel: Level0Exactly,
}

// Format07V1 is the definition of a message at Format07 for ADSB Level1Exactly
var Format07V1 = adsbFormatReferenceDefinition{
	typeCode:  7,
	register:  bds.BDS06,
	adsbLevel: Level1Exactly,
}

// Format07V2 is the definition of a message at Format07 for ADSB Level2
var Format07V2 = adsbFormatReferenceDefinition{
	typeCode:  7,
	register:  bds.BDS06,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format08
//
// ------------------------------------------------------------------------------------

// Format08V0 is the definition of a message at Format08 for ADSB Level0Exactly
var Format08V0 = adsbFormatReferenceDefinition{
	typeCode:  8,
	register:  bds.BDS06,
	adsbLevel: Level0Exactly,
}

// Format08V1 is the definition of a message at Format08 for ADSB Level1Exactly
var Format08V1 = adsbFormatReferenceDefinition{
	typeCode:  8,
	register:  bds.BDS06,
	adsbLevel: Level1Exactly,
}

// Format08V2 is the definition of a message at Format08 for ADSB Level2
var Format08V2 = adsbFormatReferenceDefinition{
	typeCode:  8,
	register:  bds.BDS06,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format09
//
// ------------------------------------------------------------------------------------

// Format09V0 is the definition of a message at Format09 for ADSB Level0Exactly
var Format09V0 = adsbFormatReferenceDefinition{
	typeCode:  9,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format09V1 is the definition of a message at Format09 for ADSB Level1Exactly
var Format09V1 = adsbFormatReferenceDefinition{
	typeCode:  9,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format09V2 is the definition of a message at Format09 for ADSB Level2
var Format09V2 = adsbFormatReferenceDefinition{
	typeCode:  9,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format10
//
// ------------------------------------------------------------------------------------

// Format10V0 is the definition of a message at Format10 for ADSB Level0Exactly
var Format10V0 = adsbFormatReferenceDefinition{
	typeCode:  10,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format10V1 is the definition of a message at Format10 for ADSB Level1Exactly
var Format10V1 = adsbFormatReferenceDefinition{
	typeCode:  10,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format10V2 is the definition of a message at Format10 for ADSB Level2
var Format10V2 = adsbFormatReferenceDefinition{
	typeCode:  10,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format11
//
// ------------------------------------------------------------------------------------

// Format11V0 is the definition of a message at Format11 for ADSB Level0Exactly
var Format11V0 = adsbFormatReferenceDefinition{
	typeCode:  11,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format11V1 is the definition of a message at Format11 for ADSB Level1Exactly
var Format11V1 = adsbFormatReferenceDefinition{
	typeCode:  11,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format11V2 is the definition of a message at Format11 for ADSB Level2
var Format11V2 = adsbFormatReferenceDefinition{
	typeCode:  11,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format12
//
// ------------------------------------------------------------------------------------

// Format12V0 is the definition of a message at Format12 for ADSB Level0Exactly
var Format12V0 = adsbFormatReferenceDefinition{
	typeCode:  12,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format12V1 is the definition of a message at Format12 for ADSB Level1Exactly
var Format12V1 = adsbFormatReferenceDefinition{
	typeCode:  12,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format12V2 is the definition of a message at Format12 for ADSB Level2
var Format12V2 = adsbFormatReferenceDefinition{
	typeCode:  12,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format13
//
// ------------------------------------------------------------------------------------

// Format13V0 is the definition of a message at Format13 for ADSB Level0Exactly
var Format13V0 = adsbFormatReferenceDefinition{
	typeCode:  13,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format13V1 is the definition of a message at Format13 for ADSB Level1Exactly
var Format13V1 = adsbFormatReferenceDefinition{
	typeCode:  13,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format13V2 is the definition of a message at Format13 for ADSB Level2
var Format13V2 = adsbFormatReferenceDefinition{
	typeCode:  13,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format14
//
// ------------------------------------------------------------------------------------

// Format14V0 is the definition of a message at Format14 for ADSB Level0Exactly
var Format14V0 = adsbFormatReferenceDefinition{
	typeCode:  14,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format14V1 is the definition of a message at Format14 for ADSB Level1Exactly
var Format14V1 = adsbFormatReferenceDefinition{
	typeCode:  14,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format14V2 is the definition of a message at Format14 for ADSB Level2
var Format14V2 = adsbFormatReferenceDefinition{
	typeCode:  14,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format15
//
// ------------------------------------------------------------------------------------

// Format15V0 is the definition of a message at Format15 for ADSB Level0Exactly
var Format15V0 = adsbFormatReferenceDefinition{
	typeCode:  15,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format15V1 is the definition of a message at Format15 for ADSB Level1Exactly
var Format15V1 = adsbFormatReferenceDefinition{
	typeCode:  15,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format15V2 is the definition of a message at Format15 for ADSB Level2
var Format15V2 = adsbFormatReferenceDefinition{
	typeCode:  15,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format16
//
// ------------------------------------------------------------------------------------

// Format16V0 is the definition of a message at Format16 for ADSB Level0Exactly
var Format16V0 = adsbFormatReferenceDefinition{
	typeCode:  16,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format16V1 is the definition of a message at Format16 for ADSB Level1Exactly
var Format16V1 = adsbFormatReferenceDefinition{
	typeCode:  16,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format16V2 is the definition of a message at Format16 for ADSB Level2
var Format16V2 = adsbFormatReferenceDefinition{
	typeCode:  16,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format17
//
// ------------------------------------------------------------------------------------

// Format17V0 is the definition of a message at Format17 for ADSB Level0Exactly
var Format17V0 = adsbFormatReferenceDefinition{
	typeCode:  17,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format17V1 is the definition of a message at Format17 for ADSB Level1Exactly
var Format17V1 = adsbFormatReferenceDefinition{
	typeCode:  17,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format17V2 is the definition of a message at Format17 for ADSB Level2
var Format17V2 = adsbFormatReferenceDefinition{
	typeCode:  17,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format18
//
// ------------------------------------------------------------------------------------

// Format18V0 is the definition of a message at Format18 for ADSB Level0Exactly
var Format18V0 = adsbFormatReferenceDefinition{
	typeCode:  18,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format18V1 is the definition of a message at Format18 for ADSB Level1Exactly
var Format18V1 = adsbFormatReferenceDefinition{
	typeCode:  18,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format18V2 is the definition of a message at Format18 for ADSB Level2
var Format18V2 = adsbFormatReferenceDefinition{
	typeCode:  18,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format19
//
// ------------------------------------------------------------------------------------

// Format19V0OrMore is the definition of a message at Format19 for ADSB Level0OrMore
var Format19V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  19,
	register:  bds.BDS09,
	adsbLevel: Level0OrMore,
}

// ------------------------------------------------------------------------------------
//
//                                Format20
//
// ------------------------------------------------------------------------------------

// Format20V0 is the definition of a message at Format20 for ADSB Level0Exactly
var Format20V0 = adsbFormatReferenceDefinition{
	typeCode:  20,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format20V1 is the definition of a message at Format20 for ADSB Level1Exactly
var Format20V1 = adsbFormatReferenceDefinition{
	typeCode:  20,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format20V2 is the definition of a message at Format20 for ADSB Level2
var Format20V2 = adsbFormatReferenceDefinition{
	typeCode:  20,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format21
//
// ------------------------------------------------------------------------------------

// Format21V0 is the definition of a message at Format21 for ADSB Level0Exactly
var Format21V0 = adsbFormatReferenceDefinition{
	typeCode:  21,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format21V1 is the definition of a message at Format21 for ADSB Level1Exactly
var Format21V1 = adsbFormatReferenceDefinition{
	typeCode:  21,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format21V2 is the definition of a message at Format21 for ADSB Level2
var Format21V2 = adsbFormatReferenceDefinition{
	typeCode:  21,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format22
//
// ------------------------------------------------------------------------------------

// Format22V0 is the definition of a message at Format22 for ADSB Level0Exactly
var Format22V0 = adsbFormatReferenceDefinition{
	typeCode:  22,
	register:  bds.BDS05,
	adsbLevel: Level0Exactly,
}

// Format22V1 is the definition of a message at Format22 for ADSB Level1Exactly
var Format22V1 = adsbFormatReferenceDefinition{
	typeCode:  22,
	register:  bds.BDS05,
	adsbLevel: Level1Exactly,
}

// Format22V2 is the definition of a message at Format22 for ADSB Level2
var Format22V2 = adsbFormatReferenceDefinition{
	typeCode:  22,
	register:  bds.BDS05,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format28
//
// ------------------------------------------------------------------------------------

// Format28V0OrMore is the definition of a message at Format28 for ADSB Level0OrMore
var Format28V0OrMore = adsbFormatReferenceDefinition{
	typeCode:  28,
	register:  bds.BDS61,
	adsbLevel: Level0OrMore,
}

// Format28V0 is the definition of a message at Format28 for ADSB Level0Exactly
var Format28V0 = adsbFormatReferenceDefinition{
	typeCode:  28,
	register:  bds.BDS61,
	adsbLevel: Level0Exactly,
}

// Format28V1 is the definition of a message at Format28 for ADSB Level1Exactly
var Format28V1 = adsbFormatReferenceDefinition{
	typeCode:  28,
	register:  bds.BDS61,
	adsbLevel: Level1Exactly,
}

// Format28V2 is the definition of a message at Format28 for ADSB Level2
var Format28V2 = adsbFormatReferenceDefinition{
	typeCode:  28,
	register:  bds.BDS61,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format29
//
// ------------------------------------------------------------------------------------

// Format29V1OrMore is the definition of a message at Format29 for ADSB Level1OrMore
var Format29V1OrMore = adsbFormatReferenceDefinition{
	typeCode:  29,
	register:  bds.BDS62,
	adsbLevel: Level1OrMore,
}

// Format29V2 is the definition of a message at Format29 for ADSB Level2
var Format29V2 = adsbFormatReferenceDefinition{
	typeCode:  29,
	register:  bds.BDS62,
	adsbLevel: Level2,
}

// ------------------------------------------------------------------------------------
//
//                                Format31
//
// ------------------------------------------------------------------------------------

// Format31V0 is the definition of a message at Format31 for ADSB Level0Exactly
var Format31V0 = adsbFormatReferenceDefinition{
	typeCode:  31,
	register:  bds.BDS65,
	adsbLevel: Level0Exactly,
}

// Format31V1 is the definition of a message at Format31 for ADSB Level1Exactly
var Format31V1 = adsbFormatReferenceDefinition{
	typeCode:  31,
	register:  bds.BDS65,
	adsbLevel: Level1Exactly,
}

// Format31V2 is the definition of a message at Format31 for ADSB Level2
var Format31V2 = adsbFormatReferenceDefinition{
	typeCode:  31,
	register:  bds.BDS65,
	adsbLevel: Level2,
}
