// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_v2.go at 2019-08-15 19:22:04.1398204 +0300 EEST m=+0.009973101
package messages

import (
	"testing"
)

func TestReadFormat15V2Valid(t *testing.T) {

	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0x78

	msg, err := ReadFormat15V2(false, data)
	if err != nil {
		t.Fatal(err)
	}

	isBDS05V2Valid(t, msg)
}

func TestReadFormat15V2TooShort(t *testing.T) {

	// Get too short data
	data := buildValidBDS05V2Message()[:6]
	data[0] = data[0] | 0x78

	_, err := ReadFormat15V2(false, data)
	if err == nil {
		t.Error(err)
	}
}

func TestReadFormat15V2BadCode(t *testing.T) {

	// Message code 1
	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0x01

	_, err := ReadFormat15V2(false, data)
	if err == nil {
		t.Error(err)
	}
}
