// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_v1.go at 2019-08-15 10:16:59.4820473 +0300 EEST m=+0.010961801
package messages

import (
	"github.com/twuillemin/modes/pkg/bds/adsb"
	"testing"
)

func TestReadFormat15V1Valid(t *testing.T) {

	data := buildValidBDS05V1Message()
	data[0] = data[0] | 0x78

	msg, err := ReadFormat15V1(false, data)
	if err != nil {
		t.Fatal(err)
	}

	if msg.GetMessageFormat() != adsb.Format15V1 {
		t.Errorf("Expected Format \"%v\", got \"%v\"",
			adsb.Format15V1.ToString(),
			msg.GetMessageFormat().ToString())
	}

	isBDS05V1Valid(t, msg)
}

func TestReadFormat15V1TooShort(t *testing.T) {

	// Get too short data
	data := buildValidBDS05V1Message()[:6]
	data[0] = data[0] | 0x78

	_, err := ReadFormat15V1(false, data)
	if err == nil {
		t.Error(err)
	}
}

func TestReadFormat15V1BadCode(t *testing.T) {

	// Message code 1
	data := buildValidBDS05V1Message()
	data[0] = data[0] | 0x01

	_, err := ReadFormat15V1(false, data)
	if err == nil {
		t.Error(err)
	}
}
