// Package messages holds the definition of the messages
//
// Code generated by go generate; DO NOT EDIT.
//
// This file was generated by gen_tests_v2.go at 2024-06-01 14:32:25.6386202 +0300 EEST m=+0.002271101
package messages

import (
	"testing"
)

func TestReadFormat09V2Valid(t *testing.T) {

	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0x48

	msg, err := ReadFormat09V2(false, data)
	if err != nil {
		t.Fatal(err)
	}

	isBDS05V2Valid(t, msg)
}

func TestReadFormat09V2TooShort(t *testing.T) {

	// Get too short data
	data := buildValidBDS05V2Message()[:6]
	data[0] = data[0] | 0x48

	_, err := ReadFormat09V2(false, data)
	if err == nil {
		t.Error(err)
	}
}

func TestReadFormat09V2BadCode(t *testing.T) {

	// Message code 1
	data := buildValidBDS05V2Message()
	data[0] = data[0] | 0x01

	_, err := ReadFormat09V2(false, data)
	if err == nil {
		t.Error(err)
	}
}
